# Generated by Django 4.1.3 on 2023-03-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    def combine_names(apps, schema_editor):
        week_days = [
            "Понедельник",
            "Вторник",
            "Среда",
            "Четверг",
            "Пятница",
            "Суббота",
            "Воскресенье",
        ]
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        WeekDays = apps.get_model("schedule", "WeekDays")
        for day in week_days:
            WeekDays(name=day).save()

    operations = [
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(combine_names),
    ]
