# Generated by Django 4.1.3 on 2023-05-21 09:59
from datetime import time

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_timetable_day'),
    ]

    def create_times(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        LessonsTimes = apps.get_model("schedule", "LessonsTimes")
        LessonsTimes(start_time=time(hour=8, minute=30), end_time=time(hour=9, minute=50)).save()
        LessonsTimes(start_time=time(hour=10, minute=0), end_time=time(hour=11, minute=20)).save()
        LessonsTimes(start_time=time(hour=11, minute=30), end_time=time(hour=12, minute=50)).save()
        LessonsTimes(start_time=time(hour=13, minute=30), end_time=time(hour=14, minute=50)).save()
        LessonsTimes(start_time=time(hour=15, minute=0), end_time=time(hour=16, minute=20)).save()
        LessonsTimes(start_time=time(hour=16, minute=30), end_time=time(hour=17, minute=50)).save()
        LessonsTimes(start_time=time(hour=18, minute=0), end_time=time(hour=19, minute=20)).save()
        LessonsTimes(start_time=time(hour=19, minute=30), end_time=time(hour=20, minute=50)).save()

    operations = [
        migrations.CreateModel(
            name='LessonsTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.RunPython(create_times),
    ]
