# Generated by Django 4.1.3 on 2023-05-21 10:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_lessonstimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='lesson_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.lessonstimes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
