# Generated by Django 4.1.3 on 2023-05-21 10:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_timetable_lesson_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='lesson_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.lessonstimes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
