# Generated by Django 4.1.3 on 2023-06-08 11:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_timetable_once'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='lesson_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.lessonstimes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
